#!/bin/bash

git diff --cached --name-only | while read FILE; do
if [[ "$FILE" =~ ^.+(php|inc|module|install|test)$ ]]; then
    php -l "$FILE" 1> /dev/null
    if [ $? -ne 0 ]; then
        echo -e "\e[1;31m\tAborting commit due to files with syntax errors" >&2
        exit 1
    else
            ~/.composer/vendor/squizlabs/php_codesniffer/scripts/phpcs --standard="~/.composer/vendor/drupal/coder/coder_sniffer/Drupal" "$FILE" #1> /dev/null
            if [ $? -ne 0 ]; then
		~/.composer/vendor/bin/phpcbf  --standard=~/.composer/vendor/drupal/coder/coder_sniffer/Drupal "$FILE"
                echo -e "\e[1;33m\tWarning, some files do not respecting the Drupal coding standards. Commit was aborted.\e[0m" >&2
		exit 1;
            fi

            RESULT=$(grep "dpm(" "$FILE")
            if [ ! -z $RESULT ]; then
                echo -e "\e[1;33m\tWarning, the commit contains a call to dpm(). Commit was not aborted, however.\e[0m" >&2
            fi
    fi
fi
done
